# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RDC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RDC
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'Alamofire', '~> 5.0.0-rc.3'

  # Contraintes
  pod 'SnapKit', '~> 5.0.0'
  pod 'TinyConstraints'
  pod 'PureLayout'

  # Navigation
  pod 'SideMenu', '~> 6.0'

end
